- name: installing EPEL
  yum:
    name: epel-release
    update_cache: yes
- name: Install firewalld
  yum:
    name: firewalld
    state: '{{ state }}'
  notify: Start firewalld
- name: installing nginx
  yum:
    name: nginx
    state: '{{ state }}'
    update_cache: yes
- name: start nginx
  service:
    name: nginx
    state: started
    enabled: yes
- name: Allow all access to  port 80
  firewalld:
    zone: public
    port: 80/tcp
    permanent: true
    state: enabled
- name: Apply Nginx template
  template:
    src: '{{ nginx }}.j2'
    dest: '{{ nginx_path }}/{{ nginx }}'
  notify: Reload Nginx
