- name: installing nginx
  apt:
    name: nginx
    state: '{{ state }}'
    update_cache: yes
- name: start nginx
  service:
    name: nginx
    state: started
    enabled: yes
- name: Allow all access to  port 80
  ufw:
    rule: allow
    port: '80'
    proto: tcp
- name: Apply Nginx template
  template:
    src: '{{ nginx }}.j2'
    dest: '{{ nginx_path }}/{{ nginx }}'
  notify: Reload Nginx
