---
# tasks file for deploy-nginx-vault

- name: nginx
  apt:
    name: nginx
    state: '{{ nginx_state }}'
    update_cache: true
- name: start nginx
  service:
    name: nginx
    state: started
    enabled: true
- name: Allow all access to  port 80
  ufw:
    rule: allow
    port: '80'
    proto: tcp
- name: Remove defaults
  file:
    state: absent
    path: "{{ site_enabled_path }}/default"
  notify: Reload Nginx
- name: Performing Tasks for first host
  include_tasks: lb.yml
  when: inventory_hostname in groups["load-balancer"]
- name: Performing Tasks for second host
  include_tasks: apps.yml
  when: inventory_hostname in groups["apps"]
