---
# vars file for deploy_nginx
centos_user: www-data
nginx_path: /etc/nginx
nginx: nginx.conf
state: present
nginx_http: nginx-http
pid_path: /var/run/nginx.pid
wp_value: auto
wc_value: 768
nginx_settings:
  - key: sendfile
    value: "on"
  - key: tcp_nopush
    value: "on"
  - key: tcp_nodelay
    value: "on"
  - key: keepalive_timeout
    value: "70"
  - key: gzip
    value: "on"
  - key: types_hash_max_size
    value: 2048
  - key: include
    value: /etc/nginx/mime.types
  - key: default_type
    value: application/octet-stream
  - key: access_log
    value: /var/log/nginx/access.log
  - key: error_log
    value: /var/log/nginx/error.log
  - key: include
    value: /etc/nginx/conf.d/*.conf
  - key: include
    value: /etc/nginx/sites-enabled/*
domain_name: abrams.devops.rebrain.srwx.net
