---
# handlers file for install-nginx-diff
- name: Reload Nginx
  service:
    name: nginx
    state: reloaded
- name: Start firewalld
  service:
    name: firewalld
    state: started
    enabled: yes
