- name: set up webserver
  hosts: all
  tasks: 
    - name: nginx
      apt:
        name: nginx
        state: latest
        update_cache: yes
    - name: start nginx
      service: 
        name: nginx
        state: started
        enabled: yes 
    - name: Allow all access to tcp port 80
      ufw:
        rule: allow
        port: '80'
        proto: tcp
