---
# tasks file for deploy_nginx
- name: nginx
  apt:
    name: nginx
    state: '{{ nginx_state }}'
    update_cache: yes
- name: start nginx
  service:
    name: nginx
    state: started
    enabled: yes
- name: Allow all access to  port 80
  ufw:
    rule: allow
    port: '80'
    proto: tcp
- name: Allow all access to port 443
  ufw:
    rule: allow
    port: '443'
    proto: tcp
- name: Apply Nginx template
  template:
    src: '{{ nginx }}.j2'
    dest: '{{ nginx_path }}/{{ nginx }}'
  notify: Reload Nginx
- name: Apply Nginxs template
  template:
    src: '{{ nginx_http }}.j2'
    dest: '{{ site_available_path }}/{{ nginx_http }}'
  notify: Reload Nginx
- name: Creating link
  file:
    src: '{{ site_available_path }}/{{ nginx_http }}'
    dest: '{{ site_enabled_path }}/{{ nginx_http }}'
    state: link
  notify: Reload Nginx
- name: Remove defaults
  file:
    state: absent
    path: "{{ site_enabled_path }}/default"
  notify: Reload Nginx
- name: Install nginx site for specified site
  template:
    src: nginx-le.j2
    dest:  "{{ site_enabled_path }}/le"
  notify: Reload Nginx
